import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import { Footer } from '@/components/Footer';
import { Nav } from '@/components/header/Nav';
import { AuthProvider } from '@/components/contexts/auth.context';
import { ToastContainer } from 'react-toastify';
import { CartProvider } from './cart/_components/CartProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <>
      <CartProvider>
        <div>
          <Nav />
          {children}
          <Footer />
        </div>
      </CartProvider>
    </>
  );
}
